// Month-end salary workbook (.xlsx) in the accounts team's format:
//   Remuneration · Salary & Wages · Overtime · (Bonus) · Payment Summary
// Same sheets/columns/order as the hand-kept sheet, but with live formulas
// (every formula also carries its computed result), no broken refs, frozen
// panes, a collapsible day grid and print-ready A4 landscape pages.
//
// Pure + isomorphic: runs in the browser or Node. No "@/" imports on purpose.
import ExcelJS from "exceljs"
import { monthInfo, computeSalary, WD } from "./salaryCalc.js"

// ---- design tokens (data-dense dashboard palette; print-safe) ----
const C = {
  navy: "FF1E40AF",
  navyDark: "FF1E3A8A",
  ink: "FF0F172A",
  slate: "FF475569",
  border: "FFCBD5E1",
  group: "FFDBEAFE",
  zebra: "FFF8FAFC",
  weekend: "FFE2E8F0",
  total: "FFE2E8F0",
  net: "FFEFF6FF",
  absentFill: "FFFEE2E2",
  absentInk: "FFB91C1C",
  amber: "FFB45309",
  workedFill: "FFDCFCE7", // worked a weekend / holiday
  workedInk: "FF15803D",
  white: "FFFFFFFF",
}
const FONT = "Calibri"
const MONEY = '_(* #,##0_);_(* (#,##0);_(* "-"??_);_(@_)'
const DAYFMT = '[=1]"P";[=0]"A";0.0#'

const pad = (n) => String(n).padStart(2, "0")
export const colL = (n) => {
  let s = ""
  while (n > 0) {
    const m = (n - 1) % 26
    s = String.fromCharCode(65 + m) + s
    n = Math.floor((n - 1) / 26)
  }
  return s
}
const fmtDate = (iso) => {
  if (!iso) return ""
  const [y, m, d] = String(iso).slice(0, 10).split("-").map(Number)
  return `${pad(d)}.${pad(m)}.${y}`
}
const isoDate = (iso) => {
  if (!iso) return null
  const [y, m, d] = String(iso).slice(0, 10).split("-").map(Number)
  return new Date(Date.UTC(y, m - 1, d))
}

// ---- cell helpers ----
const thin = { style: "thin", color: { argb: C.border } }
const box = { top: thin, left: thin, bottom: thin, right: thin }
const fill = (argb) => ({ type: "pattern", pattern: "solid", fgColor: { argb } })

function cellStyle(cell, o = {}) {
  cell.font = {
    name: FONT,
    size: o.size || 10,
    bold: !!o.bold,
    italic: !!o.italic,
    color: { argb: o.color || C.ink },
  }
  if (o.fill) cell.fill = fill(o.fill)
  if (o.border !== false) cell.border = o.border || box
  cell.alignment = {
    horizontal: o.h || undefined,
    vertical: o.v || "middle",
    wrapText: !!o.wrap,
  }
  if (o.fmt) cell.numFmt = o.fmt
}
const F = (formula, result) => ({ formula, result })

// Company letterhead + title, merged across `width` columns. Returns next row.
function letterhead(ws, width, company, title, subtitle) {
  const last = colL(width)
  const line = (r, text, o) => {
    ws.mergeCells(`A${r}:${last}${r}`)
    const c = ws.getCell(`A${r}`)
    c.value = text
    cellStyle(c, { ...o, h: "center", border: false })
  }
  line(1, company.name, { size: 16, bold: true, color: C.navyDark })
  ws.getRow(1).height = 24
  line(2, [company.address1, company.address2].filter(Boolean).join(" "), {
    size: 10,
    color: C.slate,
  })
  line(3, title, { size: 13, bold: true })
  ws.getRow(3).height = 20
  if (subtitle) line(4, subtitle, { size: 10, color: C.slate })
  return subtitle ? 6 : 5
}

// Signature line under the table: labels spread over the printed width.
function signatures(ws, row, width, labels) {
  const span = Math.max(2, Math.floor(width / labels.length))
  labels.forEach((label, i) => {
    const from = 1 + i * span + (i === labels.length - 1 ? width - span * labels.length : 0)
    const to = Math.min(width, from + Math.max(1, Math.floor(span * 0.75)))
    ws.mergeCells(`${colL(from)}${row}:${colL(to)}${row}`)
    const c = ws.getCell(`${colL(from)}${row}`)
    c.value = label
    cellStyle(c, {
      bold: true,
      h: "center",
      border: { top: { style: "thin", color: { argb: C.ink } } },
    })
  })
  ws.getRow(row).height = 20
}

function printSetup(ws, lastCol, lastRow, titleRows) {
  ws.pageSetup = {
    paperSize: 9, // A4
    orientation: "landscape",
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    horizontalCentered: true,
    margins: { left: 0.25, right: 0.25, top: 0.4, bottom: 0.4, header: 0.2, footer: 0.2 },
    printArea: `A1:${colL(lastCol)}${lastRow}`,
    printTitlesRow: titleRows,
  }
  ws.headerFooter = { oddFooter: "&L&8&K475569Generated by GreenTouch&R&8&K475569Page &P of &N" }
}

// Grouped header cell spanning [from..to] on `row`.
function groupHead(ws, row, from, to, text, o = {}) {
  if (to > from) ws.mergeCells(`${colL(from)}${row}:${colL(to)}${row}`)
  const c = ws.getCell(`${colL(from)}${row}`)
  c.value = text
  cellStyle(c, { bold: true, h: "center", fill: o.fill || C.group, color: C.navyDark, size: 9 })
  for (let k = from + 1; k <= to; k++) ws.getCell(`${colL(k)}${row}`).border = box
}
function colHead(ws, row, col, text, o = {}) {
  const c = ws.getCell(`${colL(col)}${row}`)
  c.value = text
  cellStyle(c, {
    bold: true, h: "center", wrap: true,
    fill: o.fill || C.navy, color: o.color || C.white, size: o.size || 9,
    fmt: o.fmt,
  })
  return c
}

// ======================================================================
// Sheet: Remuneration (directors — no attendance)
// ======================================================================
function sheetRemuneration(wb, input, calc, mi) {
  const ws = wb.addWorksheet("Remuneration", {
    properties: { tabColor: { argb: C.navyDark } },
  })
  const heads = [
    ["S.L", 5], ["Name of Director", 24], ["Designation", 22],
    ["Inc. Rate", 9], ["No. Inc", 7], ["Cu. Inc", 7], ["Total Increment", 11],
    ["Remuneration", 13], ["Basic", 11], ["House Rent", 11], ["Medical Allowance", 11],
    ["Conveyance", 11], ["Gross", 12], ["AIT", 10], ["Advance", 11],
    ["Total Deduction", 12], ["Net Remuneration", 14], ["Signature", 18],
  ]
  const W = heads.length
  heads.forEach(([, w], i) => (ws.getColumn(i + 1).width = w))
  letterhead(ws, W, input.company,
    `Remuneration for the Month of ${mi.label}`,
    `Date: ${fmtDate(input.preparedDate)}`)

  const G = 6, H = 7, P = 8 // group row, header row, split-% row
  groupHead(ws, G, 1, 3, "Director")
  groupHead(ws, G, 4, 7, "Increment")
  groupHead(ws, G, 8, 13, "Remuneration breakdown")
  groupHead(ws, G, 14, 16, "Deductions")
  groupHead(ws, G, 17, 18, "Payable")
  heads.forEach(([t], i) => colHead(ws, H, i + 1, t))
  ws.getRow(H).height = 32
  // split percentages the formulas reference (like the original sheet)
  const pct = { 9: input.split.basic, 10: input.split.house, 11: input.split.medical, 12: input.split.conveyance }
  for (let k = 1; k <= W; k++) {
    const c = ws.getCell(`${colL(k)}${P}`)
    if (pct[k] != null) {
      c.value = pct[k]
      cellStyle(c, { h: "center", fmt: "0%", size: 9, bold: true, color: C.navyDark, fill: C.group })
    } else cellStyle(c, { fill: C.group })
  }
  ws.mergeCells(`A${P}:H${P}`)
  ws.getCell(`A${P}`).value = "Breakdown of remuneration →"
  cellStyle(ws.getCell(`A${P}`), { h: "right", italic: true, size: 9, color: C.navyDark, fill: C.group })

  let r = P + 1
  const first = r
  calc.directors.forEach((d, i) => {
    const row = ws.getRow(r)
    row.height = 22
    const zebra = i % 2 ? C.zebra : undefined
    const set = (k, v, o = {}) => {
      const c = ws.getCell(`${colL(k)}${r}`)
      c.value = v
      cellStyle(c, { fill: zebra, ...o })
    }
    set(1, i + 1, { h: "center" })
    set(2, d.name, { bold: true })
    set(3, d.designation, { color: C.slate })
    set(4, F(`I${r}/30`, d.incRate), { fmt: MONEY })
    set(5, Number(d.incCount) || 0, { h: "center", fmt: '0;-0;"-"' })
    set(6, F(`E${r}*1.5`, d.cuInc), { h: "center", fmt: '0.0;-0.0;"-"' })
    set(7, F(`D${r}*F${r}`, d.totalInc), { fmt: MONEY })
    set(8, Number(d.remuneration) || 0, { fmt: MONEY, bold: true })
    set(9, F(`H${r}*$I$${P}`, d.basic), { fmt: MONEY })
    set(10, F(`H${r}*$J$${P}`, d.house), { fmt: MONEY })
    set(11, F(`H${r}*$K$${P}`, d.medical), { fmt: MONEY })
    set(12, F(`H${r}*$L$${P}`, d.conveyance), { fmt: MONEY })
    set(13, F(`SUM(I${r}:L${r})`, d.gross), { fmt: MONEY, bold: true })
    set(14, d.ait, { fmt: MONEY })
    set(15, d.advance, { fmt: MONEY })
    set(16, F(`SUM(N${r}:O${r})`, d.totalDed), { fmt: MONEY })
    set(17, F(`M${r}-P${r}`, d.net), { fmt: MONEY, bold: true, fill: C.net, color: C.navyDark })
    set(18, "", {})
    r++
  })
  const last = r - 1
  totalRow(ws, r, W, 3, [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], first, last, {
    7: "totalInc", 8: "remuneration", 9: "basic", 10: "house", 11: "medical",
    12: "conveyance", 13: "gross", 14: "ait", 15: "advance", 16: "totalDed", 17: "net",
  }, calc.directors)
  const totalR = r
  signatures(ws, r + 4, W, ["Prepared By", "Checked By", "Director", "Managing Director"])
  ws.views = [{ state: "frozen", xSplit: 2, ySplit: P, showGridLines: false }]
  printSetup(ws, W, r + 4, `${G}:${P}`)
  return { totalR }
}

// Totals row with SUM formulas over [first..last] for the given columns.
function totalRow(ws, r, W, labelSpan, cols, first, last, keys, rows) {
  ws.mergeCells(`A${r}:${colL(labelSpan)}${r}`)
  const l = ws.getCell(`A${r}`)
  l.value = "Total"
  cellStyle(l, { bold: true, h: "right", fill: C.total })
  for (let k = 2; k <= W; k++) {
    const c = ws.getCell(`${colL(k)}${r}`)
    if (k <= labelSpan) {
      c.border = box
      continue
    }
    if (cols.includes(k)) {
      const key = keys[k]
      const result = key ? rows.reduce((a, x) => a + (Number(x[key]) || 0), 0) : undefined
      c.value = last >= first ? F(`SUM(${colL(k)}${first}:${colL(k)}${last})`, result) : 0
      cellStyle(c, { bold: true, fill: C.total, fmt: MONEY, color: C.ink })
    } else cellStyle(c, { fill: C.total })
  }
  ws.getRow(r).height = 22
  // double rule above totals
  for (let k = 1; k <= W; k++) {
    const c = ws.getCell(`${colL(k)}${r}`)
    c.border = { ...box, top: { style: "double", color: { argb: C.ink } } }
  }
}

// ======================================================================
// Sheet: Salary & Wages (staff) — same columns & rules as the Payroll page
// ======================================================================
function sheetSalary(wb, input, calc, mi) {
  const ws = wb.addWorksheet("Salary & Wages", {
    properties: { tabColor: { argb: C.navy }, outlineLevelCol: 1 },
  })
  const N = mi.days
  const rule = input.otRule || { method: "salary", divisor: 30, hoursPerDay: 8 }
  const dr = input.dayRule || { divisor: N, deductAbsent: true, halfDeduct: 0.5, basis: "calendar" }
  const flat = rule.method === "flat"
  // column map
  const col = {}
  let k = 1
  ;["sl", "name", "desig", "incRate", "incNo", "cuInc", "basicInc", "specialInc", "totalInc"]
    .forEach((key) => (col[key] = k++))
  col.day0 = k
  k += N
  ;["present", "absent", "lateCnt", "halfCnt", "earlyCnt", "holCnt", "leave", "lwpDays",
    "current", "existing", "basic", "house", "medical", "conveyance", "gross",
    "otWorked", "otApproved", "otPay", "encash", "holPay", "bonus",
    "lwp", "lateAmt", "halfAmt", "penalty", "advance", "ait", "totalDed",
    "net", "sign"]
    .forEach((key) => (col[key] = k++))
  const W = k - 1
  const L = (key) => colL(col[key])

  const widths = {
    sl: 5, name: 24, desig: 24, incRate: 7, incNo: 6, cuInc: 6, basicInc: 9,
    specialInc: 9, totalInc: 9, present: 7, absent: 6, lateCnt: 5.5, halfCnt: 5.5, earlyCnt: 5.5, holCnt: 7, leave: 6,
    lwpDays: 6, current: 11, existing: 11, basic: 10.5, house: 10.5, medical: 10.5,
    conveyance: 10.5, gross: 11.5, otWorked: 7.5, otApproved: 8, otPay: 10, bonus: 10, encash: 9.5, holPay: 10,
    lwp: 10, lateAmt: 9, halfAmt: 9, penalty: 9, advance: 10.5, ait: 9, totalDed: 11,
    net: 12.5, sign: 16,
  }
  Object.entries(widths).forEach(([key, w]) => (ws.getColumn(col[key]).width = w))
  for (let d = 0; d < N; d++) {
    const c = ws.getColumn(col.day0 + d)
    c.width = 3.4
    c.outlineLevel = 1
  }
  for (const key of ["incRate", "incNo", "cuInc", "basicInc", "specialInc", "totalInc"])
    ws.getColumn(col[key]).outlineLevel = 1

  letterhead(ws, W, input.company, `Staff Salary for the Month of ${mi.label}`)

  // Period + rule box — every formula below references these cells.
  const basisText = {
    fixed30: "fixed 30 days", fixed26: "fixed 26 days", working: "working days", calendar: "calendar days",
  }[dr.basis] || "days"
  const box = [
    ["Salary month", mi.label, "@"],
    ["Start", mi.start, "dd-mmm-yyyy"],
    ["End", mi.end, "dd-mmm-yyyy"],
    ["Total days", F(`${L("desig")}7-${L("desig")}6+1`, N), "0"],
    [`Per-day ÷ (${basisText})`, dr.divisor, "0"],
    flat ? ["OT rate / hour", rule.flatRate || 0, MONEY] : ["OT hours / day", rule.hoursPerDay || 8, "0"],
  ]
  box.forEach(([label, v, fmt], i) => {
    const r = 5 + i
    const a = ws.getCell(`${L("name")}${r}`)
    a.value = label
    cellStyle(a, { bold: true, size: 9, fill: C.group, color: C.navyDark })
    const b = ws.getCell(`${L("desig")}${r}`)
    b.value = v
    cellStyle(b, { fmt, h: "left", bold: i >= 3 })
  })
  const TDref = `$${L("desig")}$8`
  const DIV = `$${L("desig")}$9`
  const OTX = `$${L("desig")}$10` // hours/day (or flat rate)
  const lg = ws.getCell(`${colL(col.day0)}5`)
  lg.value = "P = present (1) · A = absent (0) · shaded = weekend · approved paid leave offsets absences"
  cellStyle(lg, { size: 8, italic: true, color: C.slate, border: false })
  const lg2 = ws.getCell(`${colL(col.day0)}6`)
  lg2.value = `Late: every lates-group = 1 day · Half day / left early deducts ${Math.round((dr.halfDeduct ?? 0.5) * 100)}% of a day · green = worked a holiday (+1 day's pay)${dr.deductAbsent ? "" : " · absences are NOT deducted"}`
  cellStyle(lg2, { size: 8, italic: true, color: C.slate, border: false })

  const PR = 11, G = 12, H = 13, D = 14 // split-% row, group, header, weekday
  groupHead(ws, G, col.sl, col.desig, "Employee")
  groupHead(ws, G, col.incRate, col.totalInc, "Increment")
  groupHead(ws, G, col.day0, col.day0 + N - 1, `Attendance — ${mi.label}`)
  groupHead(ws, G, col.present, col.lwpDays, "Days")
  groupHead(ws, G, col.current, col.existing, "Salary")
  groupHead(ws, G, col.basic, col.gross, "Salary breakdown")
  groupHead(ws, G, col.otWorked, col.bonus, "Overtime & additions")
  groupHead(ws, G, col.lwp, col.totalDed, "Deductions")
  groupHead(ws, G, col.net, col.sign, "Payable")

  const labels = {
    sl: "S.L", name: "Name", desig: "Designation", incRate: "Inc. Rate",
    incNo: "No. Inc", cuInc: "Cu. Inc", basicInc: "Basic Inc.", specialInc: "Special Inc.",
    totalInc: "Total", present: "Present", absent: "Absent", lateCnt: "Late", halfCnt: "Half Day",
    earlyCnt: "Left Early", holCnt: "Holiday Worked",
    leave: "Paid Leave", lwpDays: "LWP Days", current: "Current Salary",
    existing: "Existing Salary", basic: "Basic", house: "House Rent", medical: "Medical Allowance",
    conveyance: "Conveyance", gross: "Gross", otWorked: "OT Worked (hrs)",
    otApproved: "OT Approved (hrs)", otPay: "OT Pay", bonus: "Bonus", encash: "Leave Encash. (field)", holPay: "Holiday Pay",
    lwp: "Absent (LWP)", lateAmt: "Late", halfAmt: "Half Day", penalty: "Penalty",
    advance: "Advance", ait: "AIT", totalDed: "Total Deduction", net: "Net Payable", sign: "Signature",
  }
  const weekend = new Set(input.weekendDays ?? [5])
  const holidays = new Set(input.holidays || [])
  const isOff = (d) => {
    const dt = new Date(Date.UTC(mi.y, mi.m - 1, d + 1))
    const iso = `${mi.y}-${pad(mi.m)}-${pad(d + 1)}`
    return weekend.has(dt.getUTCDay()) || holidays.has(iso)
  }
  for (const [key, t] of Object.entries(labels)) {
    colHead(ws, H, col[key], t)
    ws.mergeCells(`${L(key)}${H}:${L(key)}${D}`)
  }
  const pct = { basic: input.split.basic, house: input.split.house, medical: input.split.medical, conveyance: input.split.conveyance }
  for (let d = 0; d < N; d++) {
    const cc = col.day0 + d
    const off = isOff(d)
    colHead(ws, H, cc, d + 1, { fill: off ? C.navyDark : C.navy })
    const w = ws.getCell(`${colL(cc)}${D}`)
    const dt = new Date(Date.UTC(mi.y, mi.m - 1, d + 1))
    w.value = WD[dt.getUTCDay()]
    cellStyle(w, { h: "center", size: 8, bold: off, fill: off ? C.weekend : C.group, color: C.navyDark })
  }
  ws.getRow(H).height = 30
  ws.getRow(D).height = 14
  for (const [key, v] of Object.entries(pct)) {
    const c = ws.getCell(`${L(key)}${PR}`)
    c.value = v
    cellStyle(c, { h: "center", fmt: "0%", size: 9, bold: true, color: C.navyDark, fill: C.group })
  }

  const CNT = '[=0]"-";General'
  let r = D + 1
  const first = r
  calc.staff.forEach((s, i) => {
    ws.getRow(r).height = 20
    const zebra = i % 2 ? C.zebra : undefined
    const set = (key, v, o = {}) => {
      const c = ws.getCell(`${L(key)}${r}`)
      c.value = v
      cellStyle(c, { fill: zebra, ...o })
    }
    const g = `${L("gross")}${r}`
    set("sl", i + 1, { h: "center" })
    set("name", s.name, { bold: true })
    set("desig", s.designation, { color: C.slate, size: 9 })
    set("incRate", Number(s.incRate) || 0, { fmt: MONEY })
    set("incNo", Number(s.incCount) || 0, { h: "center", fmt: '0;-0;"-"' })
    set("cuInc", F(`${L("incNo")}${r}*1.5`, s.cuInc), { h: "center", fmt: '0.0;-0.0;"-"' })
    set("basicInc", F(`${L("incRate")}${r}*${L("cuInc")}${r}`, s.basicInc), { fmt: MONEY })
    set("specialInc", Number(s.specialInc) || 0, { fmt: MONEY })
    set("totalInc", F(`${L("basicInc")}${r}+${L("specialInc")}${r}`, s.totalInc), { fmt: MONEY })
    for (let d = 0; d < N; d++) {
      const c = ws.getCell(`${colL(col.day0 + d)}${r}`)
      c.value = s.grid[d]
      const off = s.noWeekend ? holidays.has(`${mi.y}-${pad(mi.m)}-${pad(d + 1)}`) : isOff(d)
      const worked = (s.workedDays || [])[d]
      cellStyle(c, {
        h: "center", fmt: DAYFMT, size: 9, bold: !!worked,
        fill: worked ? C.workedFill : off ? C.weekend : zebra,
        color: worked ? C.workedInk : C.slate,
      })
    }
    const dayRange = `${colL(col.day0)}${r}:${colL(col.day0 + N - 1)}${r}`
    set("present", F(`SUM(${dayRange})`, s.present), { h: "center", fmt: "General", bold: true })
    set("absent", F(`${TDref}-${L("present")}${r}`, s.absentDays), { h: "center", fmt: CNT })
    set("lateCnt", s.lateDays || 0, { h: "center", fmt: CNT, color: C.slate })
    set("halfCnt", s.halfDays || 0, { h: "center", fmt: CNT, color: C.slate })
    set("earlyCnt", s.earlyDays || 0, { h: "center", fmt: CNT, color: C.slate })
    set("holCnt", s.holidayDays || 0, { h: "center", fmt: CNT, color: s.holidayDays ? C.workedInk : C.slate, bold: !!s.holidayDays })
    set("leave", s.leaveDays || 0, { h: "center", fmt: CNT, color: C.slate })
    set("lwpDays", F(`MAX(0,${L("absent")}${r}-${L("leave")}${r})`, s.lwpDays), {
      h: "center", fmt: CNT, color: s.lwpDays ? C.amber : C.slate, bold: !!s.lwpDays,
    })
    set("current", Number(s.currentSalary ?? s.salary) || 0, { fmt: MONEY })
    set("existing", Number(s.salary) || 0, { fmt: MONEY, bold: true })
    for (const key of ["basic", "house", "medical", "conveyance"])
      set(key, F(`${L("existing")}${r}*$${L(key)}$${PR}`, s[key]), { fmt: MONEY })
    set("gross", F(`SUM(${L("basic")}${r}:${L("conveyance")}${r})`, s.gross), { fmt: MONEY, bold: true })
    // overtime & additions
    set("otWorked", s.workedOt || 0, { h: "center", fmt: '[=0]"-";0.0#', color: C.slate })
    set("otApproved", s.otHours || 0, { h: "center", fmt: '[=0]"-";0.0#', bold: !!s.otHours })
    const adj = s.otAdjust ? (s.otAdjust > 0 ? `+${s.otAdjust}` : `${s.otAdjust}`) : ""
    const otF = flat
      ? `${OTX}*${L("otApproved")}${r}${adj}`
      : `${L("existing")}${r}/(${DIV}*${OTX})*${L("otApproved")}${r}${adj}`
    set("otPay", s.otPay ? F(otF, s.otPay) : 0, { fmt: MONEY })
    set("bonus", s.bonus || 0, { fmt: MONEY })
    set("encash", s.encashDays ? F(`${s.encashDays}*(${g}/${DIV})`, s.encash) : 0, { fmt: MONEY })
    set("holPay", s.holidayDays ? F(`${L("holCnt")}${r}*(${g}/${DIV})`, s.holidayPay) : 0, { fmt: MONEY })
    // deductions — same rules as Payroll
    set("lwp", dr.deductAbsent ? F(`${L("lwpDays")}${r}*(${g}/${DIV})`, s.lwp) : 0, {
      fmt: MONEY, color: s.lwp ? C.amber : C.ink,
    })
    set("lateAmt", s.lateCutDays ? F(`${s.lateCutDays}*(${g}/${DIV})`, s.late) : 0, { fmt: MONEY })
    set("halfAmt", s.halfDays || s.earlyDays
      ? F(`(${L("halfCnt")}${r}+${L("earlyCnt")}${r})*${dr.halfDeduct ?? 0.5}*(${g}/${DIV})`, s.half)
      : 0, { fmt: MONEY })
    set("penalty", s.penalty, { fmt: MONEY })
    set("advance", s.advance, { fmt: MONEY })
    set("ait", s.ait, { fmt: MONEY })
    set("totalDed", F(`SUM(${L("lwp")}${r}:${L("ait")}${r})`, s.totalDed), { fmt: MONEY })
    set("net", F(`${g}+${L("otPay")}${r}+${L("encash")}${r}+${L("holPay")}${r}+${L("bonus")}${r}-${L("totalDed")}${r}`, s.net), {
      fmt: MONEY, bold: true, fill: C.net, color: C.navyDark,
    })
    set("sign", "", {})
    r++
  })
  const last = r - 1
  if (last >= first)
    ws.addConditionalFormatting({
      ref: `${colL(col.day0)}${first}:${colL(col.day0 + N - 1)}${last}`,
      rules: [{
        type: "cellIs", operator: "equal", formulae: ["0"], priority: 1,
        style: { fill: { type: "pattern", pattern: "solid", bgColor: { argb: C.absentFill } }, font: { color: { argb: C.absentInk }, bold: true } },
      }],
    })

  const sumCols = ["totalInc", "current", "existing", "basic", "house", "medical", "conveyance",
    "gross", "otPay", "encash", "holPay", "bonus", "lwp", "lateAmt", "halfAmt", "penalty", "advance", "ait", "totalDed", "net"]
  const keyOf = { current: "currentSalary", existing: "salary", lateAmt: "late", halfAmt: "half", holPay: "holidayPay" }
  totalRow(ws, r, W, col.desig, sumCols.map((x) => col[x]), first, last,
    Object.fromEntries(sumCols.map((x) => [col[x], keyOf[x] || x])), calc.staff)
  const totalR = r
  signatures(ws, r + 4, W, ["Prepared By", "Checked By", "Managing Director"])
  ws.views = [{ state: "frozen", xSplit: col.name, ySplit: D, showGridLines: false }]
  printSetup(ws, W, r + 4, `${G}:${D}`)
  return { totalR, col, L, TDref, W }
}

// ======================================================================
// Sheet: Overtime (approved hours × hourly rate ± adjustment)
// ======================================================================
function sheetOvertime(wb, input, calc, mi) {
  const ws = wb.addWorksheet("Overtime", { properties: { tabColor: { argb: C.amber } } })
  const rule = input.otRule || { method: "salary", divisor: 30, hoursPerDay: 8 }
  const flat = rule.method === "flat"
  const heads = [
    ["S.L", 5], ["Name", 26], ["Designation", 24], ["Existing Salary", 13],
    ["Hourly Rate", 11], ["Worked Hours", 10], ["Approved Hours", 10], ["Overtime", 12],
    ["Adjustment (+/−)", 12], ["Net Overtime", 13], ["Signature", 20],
  ]
  const W = heads.length
  heads.forEach(([, w], i) => (ws.getColumn(i + 1).width = w))
  letterhead(ws, W, input.company, `Overtime for the Month of ${mi.label}`,
    flat
      ? `Supporting schedule (paid within Salary & Wages) · approved hours only, at a flat rate per hour`
      : `Supporting schedule (paid within Salary & Wages) · approved hours only, at existing salary ÷ (${rule.divisor} days × ${rule.hoursPerDay} hours)`)

  // rate basis cells the formulas reference (row 5)
  const lab = (addr, text) => {
    const c = ws.getCell(addr)
    c.value = text
    cellStyle(c, { bold: true, size: 9, h: "right", fill: C.group, color: C.navyDark })
  }
  const val = (addr, v, fmt) => {
    const c = ws.getCell(addr)
    c.value = v
    cellStyle(c, { bold: true, h: "center", fmt })
  }
  if (flat) {
    lab("C5", "Flat rate / hour")
    val("D5", rule.flatRate || 0, MONEY)
  } else {
    lab("C5", "Days per month")
    val("D5", rule.divisor || 30, "0")
    lab("E5", "Hours / day")
    val("F5", rule.hoursPerDay || 8, "0")
  }

  const H = 7
  heads.forEach(([t], i) => colHead(ws, H, i + 1, t))
  ws.getRow(H).height = 30
  const HR = '[=0]"-";0.0#'
  let r = H + 1
  const first = r
  calc.otRows.forEach((s, i) => {
    ws.getRow(r).height = 20
    const zebra = i % 2 ? C.zebra : undefined
    const set = (k, v, o = {}) => {
      const c = ws.getCell(`${colL(k)}${r}`)
      c.value = v
      cellStyle(c, { fill: zebra, ...o })
    }
    set(1, i + 1, { h: "center" })
    set(2, s.name, { bold: true })
    set(3, s.designation, { color: C.slate })
    set(4, Number(s.salary) || 0, { fmt: MONEY })
    set(5, flat ? F("$D$5", s.otRate) : F(`D${r}/($D$5*$F$5)`, s.otRate), { fmt: "#,##0.00" })
    set(6, s.workedOt || 0, { h: "center", fmt: HR, color: C.slate })
    set(7, s.otHours, { h: "center", fmt: HR, bold: true })
    set(8, F(`E${r}*G${r}`, s.ot), { fmt: MONEY })
    set(9, s.otAdjust, { fmt: MONEY, color: s.otAdjust < 0 ? C.absentInk : C.ink })
    set(10, F(`H${r}+I${r}`, s.otPay), { fmt: MONEY, bold: true, fill: C.net, color: C.navyDark })
    set(11, "", {})
    r++
  })
  if (!calc.otRows.length) {
    ws.mergeCells(`A${r}:${colL(W)}${r}`)
    const c = ws.getCell(`A${r}`)
    c.value = "No approved overtime this month"
    cellStyle(c, { h: "center", italic: true, color: C.slate })
    r++
  }
  const last = calc.otRows.length ? r - 1 : first - 1
  totalRow(ws, r, W, 3, [4, 6, 7, 8, 9, 10], first, last,
    { 4: "salary", 7: "otHours", 8: "ot", 9: "otAdjust", 10: "otPay" }, calc.otRows)
  ws.getCell(`F${r}`).numFmt = HR
  ws.getCell(`G${r}`).numFmt = HR
  const totalR = r
  signatures(ws, r + 4, W, ["Prepared By", "Checked By", "Director", "Managing Director"])
  ws.views = [{ state: "frozen", ySplit: H, showGridLines: false }]
  printSetup(ws, W, r + 4, `${H}:${H}`)
  return { totalR, first, last }
}

// ======================================================================
// Sheet: Bonus (festival bonus — only when provided)
// ======================================================================
function sheetBonus(wb, input) {
  const b = input.bonus
  const ws = wb.addWorksheet("Bonus", { properties: { tabColor: { argb: "FF15803D" } } })
  const heads = [
    ["S.L", 5], ["Name", 26], ["Designation", 26], ["Existing Salary", 13],
    ["Gross Bonus", 13], ["Already Paid", 13], ["Net Bonus", 13], ["Signature", 22],
  ]
  const W = heads.length
  heads.forEach(([, w], i) => (ws.getColumn(i + 1).width = w))
  letterhead(ws, W, input.company, b.title || "Festival Bonus",
    `Date: ${fmtDate(b.date)}  ·  Bonus = ${Math.round((b.rate ?? 0.5) * 100)}% of existing salary`)
  const RATE = "D6"
  ws.getCell("C6").value = "Rate"
  cellStyle(ws.getCell("C6"), { bold: true, h: "right", fill: C.group, color: C.navyDark })
  ws.getCell(RATE).value = b.rate ?? 0.5
  cellStyle(ws.getCell(RATE), { fmt: "0%", bold: true, h: "center" })
  const H = 8
  heads.forEach(([t], i) => colHead(ws, H, i + 1, t))
  ws.getRow(H).height = 30
  let r = H + 1
  const first = r
  const rows = (b.rows || []).map((x) => {
    const gross = (Number(x.salary) || 0) * (b.rate ?? 0.5)
    const paid = Number(x.paid) || 0
    return { ...x, gross, paid, net: gross - paid }
  })
  rows.forEach((x, i) => {
    const zebra = i % 2 ? C.zebra : undefined
    const set = (k, v, o = {}) => {
      const c = ws.getCell(`${colL(k)}${r}`)
      c.value = v
      cellStyle(c, { fill: zebra, ...o })
    }
    ws.getRow(r).height = 20
    set(1, i + 1, { h: "center" })
    set(2, x.name, { bold: true })
    set(3, x.designation, { color: C.slate })
    set(4, Number(x.salary) || 0, { fmt: MONEY })
    set(5, F(`D${r}*$D$6`, x.gross), { fmt: MONEY })
    set(6, x.paid, { fmt: MONEY })
    set(7, F(`E${r}-F${r}`, x.net), { fmt: MONEY, bold: true, fill: C.net, color: C.navyDark })
    set(8, "", {})
    r++
  })
  totalRow(ws, r, W, 3, [4, 5, 6, 7], first, r - 1,
    { 4: "salary", 5: "gross", 6: "paid", 7: "net" }, rows)
  signatures(ws, r + 4, W, ["Prepared By", "Checked By", "Director", "Managing Director"])
  ws.views = [{ state: "frozen", ySplit: H, showGridLines: false }]
  printSetup(ws, W, r + 4, `${H}:${H}`)
}

// ======================================================================
// Sheet: Payment Summary — one page for approval / the bank
// ======================================================================
function sheetSummary(wb, input, calc, mi, refs) {
  const ws = wb.addWorksheet("Payment Summary", { properties: { tabColor: { argb: "FF15803D" } } })
  const widths = [5, 34, 10, 15, 15, 15, 16]
  widths.forEach((w, i) => (ws.getColumn(i + 1).width = w))
  const W = widths.length
  letterhead(ws, W, input.company, `Payment Summary — ${mi.label}`,
    `Prepared: ${fmtDate(input.preparedDate)}`)
  const H = 7
  ;["#", "Payment head", "People", "Gross", "Additions", "Deductions", "Net payable"].forEach((t, i) =>
    colHead(ws, H, i + 1, t))
  ws.getRow(H).height = 26
  const sw = refs.sw
  const t = calc.totals
  const S = (key) => `'Salary & Wages'!${sw.L(key)}${sw.totalR}`
  const R = (c) => `Remuneration!${c}${refs.rem.totalR}`
  const lines = [
    ["Directors' Remuneration", calc.directors.length,
      F(R("M"), t.dirGross), 0, F(R("P"), t.dirDed), F(R("Q"), t.dirNet)],
    ["Staff Salary & Wages", calc.staff.length,
      F(S("gross"), t.staffGross),
      F(`${S("otPay")}+${S("encash")}+${S("holPay")}+${S("bonus")}`, t.otPay + t.encash + t.holidayPay + t.bonus),
      F(S("totalDed"), t.staffDed),
      F(S("net"), t.staffNet)],
  ]
  let r = H + 1
  const first = r
  lines.forEach((ln, i) => {
    const zebra = i % 2 ? C.zebra : undefined
    ws.getRow(r).height = 22
    ;[i + 1, ...ln].forEach((v, j) => {
      const c = ws.getCell(`${colL(j + 1)}${r}`)
      c.value = v
      cellStyle(c, {
        fill: j === 6 ? C.net : zebra,
        fmt: j >= 3 ? MONEY : undefined,
        h: j === 0 || j === 2 ? "center" : undefined,
        bold: j === 1 || j === 6,
        color: j === 6 ? C.navyDark : C.ink,
      })
    })
    r++
  })
  ws.mergeCells(`A${r}:B${r}`)
  const lbl = ws.getCell(`A${r}`)
  lbl.value = "Grand total"
  cellStyle(lbl, { bold: true, h: "right", fill: C.total })
  ws.getCell(`B${r}`).border = box
  const gt = [
    [3, calc.directors.length + calc.staff.length, "0"],
    [4, F(`SUM(D${first}:D${r - 1})`, t.dirGross + t.staffGross), MONEY],
    [5, F(`SUM(E${first}:E${r - 1})`, t.otPay + t.encash + t.holidayPay + t.bonus), MONEY],
    [6, F(`SUM(F${first}:F${r - 1})`, t.dirDed + t.staffDed), MONEY],
    [7, F(`SUM(G${first}:G${r - 1})`, t.dirNet + t.staffNet), MONEY],
  ]
  gt.forEach(([k, v, fmt]) => {
    const c = ws.getCell(`${colL(k)}${r}`)
    c.value = v
    cellStyle(c, { bold: true, fill: C.total, fmt, h: k === 3 ? "center" : undefined, size: 11 })
  })
  for (let k = 1; k <= W; k++)
    ws.getCell(`${colL(k)}${r}`).border = { ...box, top: { style: "double", color: { argb: C.ink } } }
  ws.getRow(r).height = 24

  // breakdown blocks that tie back to the totals above
  const block = (title, rows) => {
    r += 2
    ws.mergeCells(`B${r}:D${r}`)
    const h = ws.getCell(`B${r}`)
    h.value = title
    cellStyle(h, { bold: true, fill: C.group, color: C.navyDark })
    const top = r + 1
    rows.forEach(([label, v]) => {
      r++
      ws.mergeCells(`B${r}:C${r}`)
      const a = ws.getCell(`B${r}`)
      a.value = label
      cellStyle(a, {})
      ws.getCell(`C${r}`).border = box
      const b = ws.getCell(`D${r}`)
      b.value = v
      cellStyle(b, { fmt: MONEY })
    })
    r++
    ws.mergeCells(`B${r}:C${r}`)
    const tl = ws.getCell(`B${r}`)
    tl.value = "Total"
    cellStyle(tl, { bold: true, fill: C.total })
    ws.getCell(`C${r}`).border = box
    const tv = ws.getCell(`D${r}`)
    tv.value = F(`SUM(D${top}:D${r - 1})`, rows.reduce((a, [, v]) => a + (v.result || 0), 0))
    cellStyle(tv, { bold: true, fill: C.total, fmt: MONEY })
  }
  block("Additions", [
    ["Overtime pay (approved hours)", F(S("otPay"), t.otPay)],
    ["Leave encashment (field, unused monthly leave)", F(S("encash"), t.encash)],
    ["Holiday pay (worked a weekend / holiday)", F(S("holPay"), t.holidayPay)],
    ["Bonus", F(S("bonus"), t.bonus)],
  ])
  block("Deductions", [
    ["Absent (LWP)", F(S("lwp"), t.lwp)],
    ["Late", F(S("lateAmt"), t.late)],
    ["Half day", F(S("halfAmt"), t.half)],
    ["Penalty", F(S("penalty"), t.penalty)],
    ["Advance recovered", F(`${R("O")}+${S("advance")}`, t.advance)],
    ["AIT (tax at source)", F(`${R("N")}+${S("ait")}`, t.ait)],
  ])
  signatures(ws, r + 5, W, ["Prepared By", "Checked By", "Managing Director"])
  ws.views = [{ showGridLines: false }]
  printSetup(ws, W, r + 5, `${H}:${H}`)
}

// ======================================================================
// Public API
// ======================================================================
export async function buildSalaryWorkbook(input) {
  const mi = monthInfo(input.month)
  const calc = computeSalary(input)
  const wb = new ExcelJS.Workbook()
  wb.creator = "GreenTouch"
  wb.created = new Date()
  wb.calcProperties = { fullCalcOnLoad: true } // Excel recalculates on open
  const rem = sheetRemuneration(wb, input, calc, mi)
  const sw = sheetSalary(wb, input, calc, mi)
  const ot = sheetOvertime(wb, input, calc, mi)
  if (input.bonus && (input.bonus.rows || []).length) sheetBonus(wb, input)
  sheetSummary(wb, input, calc, mi, { rem, sw, ot })
  return { wb, calc }
}

export async function salaryWorkbookBuffer(input) {
  const { wb, calc } = await buildSalaryWorkbook(input)
  const buf = await wb.xlsx.writeBuffer()
  return { buf, calc }
}

export { salaryFileName, computeSalary } from "./salaryCalc.js"
